import type { ToolMeta } from "./manifest-types";

export const PRESETS: ToolMeta[] = [
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate UUIDs (v4 by default)",
    section: "ids",
    aliases: ["uuid", "guid", "uuid4"],
    inputType: "none",
    outputType: "text",
    canonicalSlug: "id-suite",
    presetOptions: { mode: "uuid-generate", uuidVersion: "4" },
  },
  {
    slug: "uuid-validate",
    name: "UUID Validator",
    description: "Validate UUIDs and show version",
    section: "ids",
    aliases: ["uuid-validate", "uuid-check"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "id-suite",
    presetOptions: { mode: "uuid-validate" },
  },
  {
    slug: "uuid-parse",
    name: "UUID Parser",
    description: "Inspect UUID version and timestamps",
    section: "ids",
    aliases: ["uuid-parse", "uuid-info"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "id-suite",
    presetOptions: { mode: "uuid-parse" },
  },
  {
    slug: "uuid-v7",
    name: "UUID v7 Generator",
    description: "Generate time-sortable UUID v7 identifiers",
    section: "ids",
    aliases: ["uuid7", "uuid-v7"],
    inputType: "none",
    outputType: "text",
    canonicalSlug: "id-suite",
    presetOptions: { mode: "uuid-generate", uuidVersion: "7" },
  },
  {
    slug: "ulid-generator",
    name: "ULID Generator",
    description: "Generate sortable ULID identifiers",
    section: "ids",
    aliases: ["ulid", "sortable-id"],
    inputType: "none",
    outputType: "text",
    canonicalSlug: "id-suite",
    presetOptions: { mode: "ulid-generate" },
  },
  {
    slug: "ulid-parse",
    name: "ULID Parser",
    description: "Inspect ULID timestamps",
    section: "ids",
    aliases: ["ulid-parse", "ulid-info"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "id-suite",
    presetOptions: { mode: "ulid-parse" },
  },
  {
    slug: "nanoid-generator",
    name: "NanoID Generator",
    description: "Generate compact NanoID identifiers",
    section: "ids",
    aliases: ["nanoid", "short-id"],
    inputType: "none",
    outputType: "text",
    canonicalSlug: "id-suite",
    presetOptions: { mode: "nanoid-generate" },
  },
  {
    slug: "random-string",
    name: "Random String Generator",
    description: "Generate secure random strings",
    section: "ids",
    aliases: ["token", "random"],
    inputType: "none",
    outputType: "text",
    canonicalSlug: "id-suite",
    presetOptions: { mode: "random-string" },
  },
  {
    slug: "base64-text",
    name: "Base64 Encode (Text)",
    description: "Encode UTF-8 text to Base64",
    section: "base64",
    aliases: ["base64", "btoa"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "bytes-suite",
    presetOptions: { mode: "base64-text" },
  },
  {
    slug: "base64-decode",
    name: "Base64 Decode (Text)",
    description: "Decode Base64 into UTF-8 text",
    section: "base64",
    aliases: ["base64-decode", "atob"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "bytes-suite",
    presetOptions: { mode: "base64-decode" },
  },
  {
    slug: "base64url-encode",
    name: "Base64URL Encode",
    description: "Encode text into URL-safe Base64",
    section: "base64",
    aliases: ["base64url", "base64-url"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "bytes-suite",
    presetOptions: { mode: "base64url-text" },
  },
  {
    slug: "base64-file",
    name: "File to Base64",
    description: "Convert files to Base64",
    section: "base64",
    aliases: ["file-base64", "binary-base64"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "bytes-suite",
    presetOptions: { mode: "file-to-base64" },
  },
  {
    slug: "base64-download",
    name: "Base64 to File Download",
    description: "Decode Base64 and download a file",
    section: "base64",
    aliases: ["base64-file", "base64-download"],
    inputType: "text",
    outputType: "preview",
    canonicalSlug: "bytes-suite",
    presetOptions: { mode: "base64-to-file" },
  },
  {
    slug: "hex-encode",
    name: "Hex Encode",
    description: "Encode text as hex bytes",
    section: "base64",
    aliases: ["hex", "hex-encode"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "bytes-suite",
    presetOptions: { mode: "hex-text" },
  },
  {
    slug: "hex-decode",
    name: "Hex Decode",
    description: "Decode hex to text",
    section: "base64",
    aliases: ["hex-decode"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "bytes-suite",
    presetOptions: { mode: "hex-decode" },
  },
  {
    slug: "data-url-inspector",
    name: "Data URL Inspector",
    description: "Inspect data: URLs and payload sizes",
    section: "base64",
    aliases: ["data-url"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "bytes-suite",
    presetOptions: { mode: "data-url" },
  },
  {
    slug: "hash-text",
    name: "Hash Generator (Text)",
    description: "Generate hashes for text input",
    section: "crypto",
    aliases: ["sha256", "sha512", "md5", "checksum"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "crypto-suite",
    presetOptions: { mode: "hash-text" },
  },
  {
    slug: "sha256-hash",
    name: "SHA-256 Hash",
    description: "Generate SHA-256 for text input",
    section: "crypto",
    aliases: ["sha256", "hash"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "crypto-suite",
    presetOptions: { mode: "hash-text", algorithm: "SHA-256" },
  },
  {
    slug: "hash-file",
    name: "File Hash Generator",
    description: "Generate hash checksums for files",
    section: "crypto",
    aliases: ["file-checksum", "file-sha256"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "crypto-suite",
    presetOptions: { mode: "hash-file" },
  },
  {
    slug: "hmac-generator",
    name: "HMAC Generator",
    description: "Generate HMAC signatures",
    section: "crypto",
    aliases: ["hmac", "signature"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "crypto-suite",
    presetOptions: { mode: "hmac" },
  },
  {
    slug: "pbkdf2-derive",
    name: "PBKDF2 Key Derivation",
    description: "Derive keys with PBKDF2",
    section: "crypto",
    aliases: ["pbkdf2", "derive-key"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "crypto-suite",
    presetOptions: { mode: "pbkdf2" },
  },
  {
    slug: "aes-gcm-encrypt",
    name: "AES-GCM Encrypt",
    description: "Encrypt text with AES-GCM",
    section: "crypto",
    aliases: ["aes", "encrypt"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "crypto-suite",
    presetOptions: { mode: "aes-encrypt" },
  },
  {
    slug: "jwt-decode",
    name: "JWT Decode",
    description: "Decode JWT header and payload",
    section: "crypto",
    aliases: ["jwt", "token"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "crypto-suite",
    presetOptions: { mode: "jwt-decode" },
  },
  {
    slug: "url-encode",
    name: "URL Encode",
    description: "Encode URL components",
    section: "encoding",
    aliases: ["uri", "percent-encode"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "encoding-suite",
    presetOptions: { mode: "url-encode" },
  },
  {
    slug: "query-parse",
    name: "Querystring Parser",
    description: "Parse querystrings into JSON",
    section: "encoding",
    aliases: ["querystring", "qs-parse"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "encoding-suite",
    presetOptions: { mode: "query-parse" },
  },
  {
    slug: "html-encode",
    name: "HTML Entities Encode",
    description: "Encode text into HTML entities",
    section: "encoding",
    aliases: ["html-encode", "entities"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "encoding-suite",
    presetOptions: { mode: "html-encode" },
  },
  {
    slug: "unicode-normalize",
    name: "Unicode Normalize",
    description: "Normalize Unicode strings",
    section: "encoding",
    aliases: ["unicode", "normalize"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "encoding-suite",
    presetOptions: { mode: "unicode-normalize" },
  },
  {
    slug: "json-format",
    name: "JSON Formatter",
    description: "Pretty print JSON",
    section: "formats",
    aliases: ["json", "format-json"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "data-format-suite",
    presetOptions: { mode: "json-format" },
  },
  {
    slug: "json-minify",
    name: "JSON Minifier",
    description: "Minify JSON strings",
    section: "formats",
    aliases: ["json-minify"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "data-format-suite",
    presetOptions: { mode: "json-minify" },
  },
  {
    slug: "yaml-to-json",
    name: "YAML to JSON",
    description: "Convert YAML into JSON",
    section: "formats",
    aliases: ["yaml", "yaml-to-json"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "data-format-suite",
    presetOptions: { mode: "yaml-to-json" },
  },
  {
    slug: "csv-to-json",
    name: "CSV to JSON",
    description: "Convert CSV into JSON",
    section: "formats",
    aliases: ["csv", "csv-json"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "data-format-suite",
    presetOptions: { mode: "csv-to-json" },
  },
  {
    slug: "text-diff",
    name: "Text Diff",
    description: "Compare two texts and show differences",
    section: "diff",
    aliases: ["compare", "diff", "changes"],
    inputType: "dual",
    outputType: "diff",
    canonicalSlug: "diff-suite",
    presetOptions: { mode: "text-diff" },
  },
  {
    slug: "unified-diff",
    name: "Unified Diff",
    description: "Generate unified diff patches",
    section: "diff",
    aliases: ["patch", "diff-patch"],
    inputType: "dual",
    outputType: "text",
    canonicalSlug: "diff-suite",
    presetOptions: { mode: "unified-diff" },
  },
  {
    slug: "epoch-converter",
    name: "Epoch Converter",
    description: "Convert timestamps to dates",
    section: "datetime",
    aliases: ["unix-time", "timestamp"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "datetime-suite",
    presetOptions: { mode: "epoch-iso" },
  },
  {
    slug: "relative-time",
    name: "Relative Time",
    description: "Show relative time (ago / from now)",
    section: "datetime",
    aliases: ["time-ago", "relative"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "datetime-suite",
    presetOptions: { mode: "relative" },
  },
  {
    slug: "cron-explain",
    name: "Cron Explain",
    description: "Explain cron expressions",
    section: "datetime",
    aliases: ["cron", "schedule"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "datetime-suite",
    presetOptions: { mode: "cron" },
  },
  {
    slug: "base-converter",
    name: "Base Converter",
    description: "Convert numbers across bases",
    section: "numbers",
    aliases: ["base", "radix"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "numbers-suite",
    presetOptions: { mode: "base-convert" },
  },
  {
    slug: "cidr-calculator",
    name: "CIDR Calculator",
    description: "Calculate network/broadcast addresses",
    section: "numbers",
    aliases: ["cidr", "subnet"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "numbers-suite",
    presetOptions: { mode: "cidr" },
  },
  {
    slug: "basic-auth",
    name: "Basic Auth Encoder",
    description: "Encode username/password to Basic Auth",
    section: "http",
    aliases: ["basic-auth", "auth"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "http-suite",
    presetOptions: { mode: "basic-auth" },
  },
  {
    slug: "curl-parser",
    name: "cURL Parser",
    description: "Parse cURL commands into JSON",
    section: "http",
    aliases: ["curl", "curl-parse"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "http-suite",
    presetOptions: { mode: "curl-parse" },
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert hex, RGB, HSL and more",
    section: "colors",
    aliases: ["hex-to-rgb", "hsl"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "color-suite",
    presetOptions: { mode: "color-convert" },
  },
  {
    slug: "contrast-checker",
    name: "Contrast Checker",
    description: "Check WCAG contrast ratios",
    section: "colors",
    aliases: ["contrast", "wcag"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "color-suite",
    presetOptions: { mode: "contrast" },
  },
  {
    slug: "image-compress",
    name: "Image Compressor",
    description: "Compress images in-browser",
    section: "images",
    aliases: ["image-compress"],
    inputType: "text",
    outputType: "preview",
    canonicalSlug: "media-suite",
    presetOptions: { mode: "image-compress" },
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from text",
    section: "images",
    aliases: ["qr", "qr-generate"],
    inputType: "text",
    outputType: "preview",
    canonicalSlug: "media-suite",
    presetOptions: { mode: "qr-generate" },
  },
  {
    slug: "prettier-format",
    name: "Prettier Formatter",
    description: "Format code with Prettier",
    section: "code",
    aliases: ["prettier", "format"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "code-suite",
    presetOptions: { mode: "format" },
  },
  {
    slug: "js-minify",
    name: "JS Minifier",
    description: "Minify JavaScript",
    section: "code",
    aliases: ["minify", "terser"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "code-suite",
    presetOptions: { mode: "minify" },
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test and debug regex patterns",
    section: "regex",
    aliases: ["regex", "regexp"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "regex-suite",
    presetOptions: { mode: "match" },
  },
  {
    slug: "extract-emails",
    name: "Extract Emails",
    description: "Extract email addresses from text",
    section: "data",
    aliases: ["emails", "email-extract"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "data-extract-suite",
    presetOptions: { mode: "emails" },
  },
  {
    slug: "extract-urls",
    name: "Extract URLs",
    description: "Extract URLs from text",
    section: "data",
    aliases: ["urls", "url-extract"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "data-extract-suite",
    presetOptions: { mode: "urls" },
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Convert Markdown to HTML",
    section: "markdown",
    aliases: ["markdown", "md-preview"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "markdown-suite",
    presetOptions: { mode: "md-to-html" },
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML into Markdown",
    section: "markdown",
    aliases: ["html-to-md"],
    inputType: "text",
    outputType: "text",
    canonicalSlug: "markdown-suite",
    presetOptions: { mode: "html-to-md" },
  },
];
